SPLIT_PROMPT_100_to_200 = '''Split the input reasoning text into logical steps, each as a standalone JSON object in JSONL format.
VERY IMPORTANT:
- You must preserve the **exact original wording** from the input text. 
- DO NOT paraphrase, rephrase, shorten, correct, or reformat the content.
- Include **all punctuation, math expressions, newlines (\\n), and spacing** exactly as they appear.
- You are only allowed to break the input into steps — but never modify or rewrite the content of the steps.
- The output must be a **strict subset of the input text**, just split into segments.
Output format:
Only JSONL lines of the form: {"step": step_number, "content": original_text_segment}
DO NOT include any explanation, instructions, headers, or extra text — only pure JSONL output.

Example input:
Question: Let $p(x) = 2x - 7$ and $q(x) = 3x - b$.  If $p(q(4)) = 7$, what is $b$?
Solution: <think>Okay, let's see. I need to find the value of \( b \) given that \( p(x) = 2x - 7 \) and \( q(x) = 3x - b \), and \( p(q(4)) = 7 \). Hmm, let's break this down step by step.\n\nFirst, I remember that when you have a composite function like \( p(q(x)) \), you substitute \( q(x) \) into \( p \). So \( p(q(4)) \) means first find \( q(4) \), then plug that result into \( p \).\n\nLet's start with \( q(4) \). Since \( q(x) = 3x - b \), substituting \( x = 4 \) gives:\n\n\( q(4) = 3(4) - b = 12 - b \).\n\nNow, we need to plug this into \( p \). The function \( p(x) = 2x - 7 \), so \( p(q(4)) = p(12 - b) \). Let's compute that:\n\n\( p(12 - b) = 2(12 - b) - 7 \).\n\nLet's simplify that expression:\n\nFirst, distribute the 2: \( 2 \\times 12 = 24 \) and \( 2 \\times (-b) = -2b \), so \( 2(12 - b) = 24 - 2b \).\n\nThen subtract 7: \( 24 - 2b - 7 = 17 - 2b \).\n\nWe are told that \( p(q(4)) = 7 \), so set the expression equal to 7:\n\n\( 17 - 2b = 7 \).\n\nNow, solve for \( b \). Let's subtract 17 from both sides:\n\n\( -2b = 7 - 17 \)\n\n\( -2b = -10 \)\n\nThen divide both sides by -2:\n\n\( b = \\frac{-10}{-2} = 5 \).\n
Let me check that to make sure. If \( b = 5 \), then \( q(x) = 3x - 5 \). So \( q(4) = 3(4) - 5 = 12 - 5 = 7 \). Then \( p(q(4)) = p(7) = 2(7) - 7 = 14 - 7 = 7 \), which matches the given condition. So that checks out.\n
I think that's right. Let me just go through the steps again to be sure. First, compute \( q(4) \) as 12 - b. Then plug into p: 2*(12 - b) - 7 = 24 - 2b - 7 = 17 - 2b. Set equal to 7: 17 - 2b = 7. Subtract 17: -2b = -10. Divide by -2: b = 5. Yep, that seems correct. I don't see any mistakes here.\n\n**Final Answer**\nThe value of \( b \) is \(\\boxed{5}\).<\\think>
To find the value of $ b $, we are given two functions:\n\n- $ p(x) = 2x - 7 $\n- $ q(x) = 3x - b $\n\nand the condition that:\n\n$$\np(q(4)) = 7\n$$
\n---\n\n### Step 1: Compute $ q(4) $\n\nSubstitute $ x = 4 $ into $ q(x) $:\n\n$$\nq(4) = 3(4) - b = 12 - b\n$$\n\n---\n\n### Step 2: Plug $ q(4) $ into $ p(x) $\n
Now substitute $ q(4) = 12 - b $ into $ p(x) $:\n\n$$\np(q(4)) = p(12 - b) = 2(12 - b) - 7\n$$\n\nSimplify:\n\n$$\n2(12 - b) - 7 = 24 - 2b - 7 = 17 - 2b\n$$\n\n---\n\n### Step 3: Set equal to the given value\n\nWe are told that $ p(q(4)) = 7 $, so:\n\n$$\n17 - 2b = 7\n$$\n\nSolve for $ b $:\n\n$$\n-2b = 7 - 17 \\\n-2b = -10 \\\nb = \frac{-10}{-2} = 5\n$$\n\n---\n\n### Final Answer\n\n$$\n\\boxed{5}\n$$

Example output:
{"step": 1, "content": "<think>Okay, let's see. I need to find the value of \( b \) given that \( p(x) = 2x - 7 \) and \( q(x) = 3x - b \), and \( p(q(4)) = 7 \). Hmm, let's break this down step by step.\n\nFirst, I remember that when you have a composite function like \( p(q(x)) \), you substitute \( q(x) \) into \( p \). So \( p(q(4)) \) means first find \( q(4) \), then plug that result into \( p \).\n\nLet's start with \( q(4) \). Since \( q(x) = 3x - b \), substituting \( x = 4 \) gives:\n\n\( q(4) = 3(4) - b = 12 - b \).\n\nNow, we need to plug this into \( p \). The function \( p(x) = 2x - 7 \), so \( p(q(4)) = p(12 - b) \). Let's compute that:\n\n\( p(12 - b) = 2(12 - b) - 7 \).\n\nLet's simplify that expression:\n\nFirst, distribute the 2: \( 2 \\times 12 = 24 \) and \( 2 \\times (-b) = -2b \), so \( 2(12 - b) = 24 - 2b \).\n\nThen subtract 7: \( 24 - 2b - 7 = 17 - 2b \).\n\nWe are told that \( p(q(4)) = 7 \), so set the expression equal to 7:\n\n\( 17 - 2b = 7 \).\n\nNow, solve for \( b \). Let's subtract 17 from both sides:\n\n\( -2b = 7 - 17 \)\n\n\( -2b = -10 \)\n\nThen divide both sides by -2:\n\n\( b = \\frac{-10}{-2} = 5 \).\n\n"}
{"step": 2, "content": "Let me check that to make sure. If \( b = 5 \), then \( q(x) = 3x - 5 \). So \( q(4) = 3(4) - 5 = 12 - 5 = 7 \). Then \( p(q(4)) = p(7) = 2(7) - 7 = 14 - 7 = 7 \), which matches the given condition. So that checks out.\n\n"}
{"step": 3, "content": "I think that's right. Let me just go through the steps again to be sure. First, compute \( q(4) \) as 12 - b. Then plug into p: 2*(12 - b) - 7 = 24 - 2b - 7 = 17 - 2b. Set equal to 7: 17 - 2b = 7. Subtract 17: -2b = -10. Divide by -2: b = 5. Yep, that seems correct. I don't see any mistakes here.\n\n**Final Answer**\nThe value of \( b \) is \(\\boxed{5}\).<\\think>\n"}
{"step": 4, "content": "To find the value of $ b $, we are given two functions:\n\n- $ p(x) = 2x - 7 $\n- $ q(x) = 3x - b $\n\nand the condition that:\n\n$$\np(q(4)) = 7\n$$
\n---\n\n### Step 1: Compute $ q(4) $\n\nSubstitute $ x = 4 $ into $ q(x) $:\n\n$$\nq(4) = 3(4) - b = 12 - b\n$$\n\n---\n\n### Step 2: Plug $ q(4) $ into $ p(x) $\n
Now substitute $ q(4) = 12 - b $ into $ p(x) $:\n\n$$\np(q(4)) = p(12 - b) = 2(12 - b) - 7\n$$\n\nSimplify:\n\n$$\n2(12 - b) - 7 = 24 - 2b - 7 = 17 - 2b\n$$\n\n---\n\n### Step 3: Set equal to the given value\n\nWe are told that $ p(q(4)) = 7 $, so:\n\n$$\n17 - 2b = 7\n$$\n\nSolve for $ b $:\n\n$$\n-2b = 7 - 17 \\\n-2b = -10 \\\nb = \frac{-10}{-2} = 5\n$$\n\n---\n\n### Final Answer\n\n$$\n\\boxed{5}\n$$"}
'''

SPLIT_PROMPT = '''Split the reasoning text into logical steps, each as a single JSON object in JSONL format. 
Each step must contain the full original content (including line breaks `\\n`, math expressions, and all characters) without modification.
Do not merge or split sentences arbitrarily — treat each natural reasoning segment as one step.
If the reasoning is unfinished, only record the completed portion without continuing or completing it.
Output only the JSONL lines (one per line), no extra text.

Example input:
Question: Let $p(x) = 2x - 7$ and $q(x) = 3x - b$.  If $p(q(4)) = 7$, what is $b$?
Solution: <think>Okay, let's see. I need to find the value of \( b \) given that \( p(x) = 2x - 7 \) and \( q(x) = 3x - b \), and \( p(q(4)) = 7 \). Hmm, let's break this down step by step.\n\nFirst, I remember that when you have a composite function like \( p(q(x)) \), you substitute \( q(x) \) into \( p \). So \( p(q(4)) \) means first find \( q(4) \), then plug that result into \( p \).\n\nLet's start with \( q(4) \). Since \( q(x) = 3x - b \), substituting \( x = 4 \) gives:\n\n\( q(4) = 3(4) - b = 12 - b \).\n\nNow, we need to plug this into \( p \). The function \( p(x) = 2x - 7 \), so \( p(q(4)) = p(12 - b) \). Let's compute that:\n\n\( p(12 - b) = 2(12 - b) - 7 \).\n\nLet's simplify that expression:\n\nFirst, distribute the 2: \( 2 \\times 12 = 24 \) and \( 2 \\times (-b) = -2b \), so \( 2(12 - b) = 24 - 2b \).\n\nThen subtract 7: \( 24 - 2b - 7 = 17 - 2b \).\n\nWe are told that \( p(q(4)) = 7 \), so set the expression equal to 7:\n\n\( 17 - 2b = 7 \).\n\nNow, solve for \( b \). Let's subtract 17 from both sides:\n\n\( -2b = 7 - 17 \)\n\n\( -2b = -10 \)\n\nThen divide both sides by -2:\n\n\( b = \\frac{-10}{-2} = 5 \).\n
Let me check that to make sure. If \( b = 5 \), then \( q(x) = 3x - 5 \). So \( q(4) = 3(4) - 5 = 12 - 5 = 7 \).

Example output:
{"step": 1, "content": "<think>Okay, let's see. I need to find the value of \( b \) given that \( p(x) = 2x - 7 \) and \( q(x) = 3x - b \), and \( p(q(4)) = 7 \). Hmm, let's break this down step by step.\n\nFirst, I remember that when you have a composite function like \( p(q(x)) \), you substitute \( q(x) \) into \( p \). So \( p(q(4)) \) means first find \( q(4) \), then plug that result into \( p \).\n\nLet's start with \( q(4) \). Since \( q(x) = 3x - b \), substituting \( x = 4 \) gives:\n\n\( q(4) = 3(4) - b = 12 - b \).\n\nNow, we need to plug this into \( p \). The function \( p(x) = 2x - 7 \), so \( p(q(4)) = p(12 - b) \). Let's compute that:\n\n\( p(12 - b) = 2(12 - b) - 7 \).\n\nLet's simplify that expression:\n\nFirst, distribute the 2: \( 2 \\times 12 = 24 \) and \( 2 \\times (-b) = -2b \), so \( 2(12 - b) = 24 - 2b \).\n\nThen subtract 7: \( 24 - 2b - 7 = 17 - 2b \).\n\nWe are told that \( p(q(4)) = 7 \), so set the expression equal to 7:\n\n\( 17 - 2b = 7 \).\n\nNow, solve for \( b \). Let's subtract 17 from both sides:\n\n\( -2b = 7 - 17 \)\n\n\( -2b = -10 \)\n\nThen divide both sides by -2:\n\n\( b = \\frac{-10}{-2} = 5 \).\n\n"}
{"step": 2, "content": "Let me check that to make sure. If \( b = 5 \), then \( q(x) = 3x - 5 \). So \( q(4) = 3(4) - 5 = 12 - 5 = 7 \)."}

Example input:
Question: Let $p(x) = 2x - 7$ and $q(x) = 3x - b$.  If $p(q(4)) = 7$, what is $b$?
Solution: <think>Okay, let's see. I need to find the value of \( b \) given that \( p(x) = 2x - 7 \) and \( q(x) = 3x - b \), and \( p(q(4)) = 7 \). Hmm, let's break this down step by step.\n\nFirst, I remember that when you have a composite function like \( p(q(x)) \), you substitute \( q(x) \) into \( p \). So \( p(q(4)) \) means first find \( q(4) \), then plug that result into \( p \).\n\nLet's start with \( q(4) \). Since \( q(x) = 3x - b \), substituting \( x = 4 \) gives:\n\n\( q(4) = 3(4) - b = 12 - b \).\n\nNow, we need to plug this into \( p \). The function \( p(x) = 2x - 7 \), so \( p(q(4)) = p(12 - b) \). Let's compute that:\n\n\( p(12 - b) = 2(12 - b) - 7 \).\n\nLet's simplify that expression:\n\nFirst, distribute the 2: \( 2 \\times 12 = 24 \) and \( 2 \\times (-b) = -2b \), so \( 2(12 - b) = 24 - 2b \).\n\nThen subtract 7: \( 24 - 2b - 7 = 17 - 2b \).\n\nWe are told that \( p(q(4)) = 7 \), so set the expression equal to 7:\n\n\( 17 - 2b = 7 \).\n\nNow, solve for \( b \). Let's subtract 17 from both sides:\n\n\( -2b = 7 - 17 \)\n\n\( -2b = -10 \)\n\nThen divide both sides by -2:\n\n\( b = \\frac{-10}{-2} = 5 \).\n
Let me check that to make sure. If \( b = 5 \), then \( q(x) = 3x - 5 \). So \( q(4) = 3(4) - 5 = 12 - 5 = 7 \). Then \( p(q(4)) = p(7) = 2(7) - 7 = 14 - 7 = 7 \), which matches the given condition. So that checks out.\n
I think that's right. Let me just go through the steps again to be sure. First, compute \( q(4) \) as 12 - b. Then plug into p: 2*(12 - b) - 7 = 24 - 2b - 7 = 17 - 2b. Set equal to 7: 17 - 2b = 7. Subtract 17: -2b = -10. Divide by -2: b = 5. Yep, that seems correct. I don't see any mistakes here.\n\n**Final Answer**\nThe value of \( b \) is \(\\boxed{5}\).<\\think>
To find the value of $ b $, we are given two functions:\n\n- $ p(x) = 2x - 7 $\n- $ q(x) = 3x - b $\n\nand the condition that:\n\n$$\np(q(4)) = 7\n$$
\n---\n\n### Step 1: Compute $ q(4) $\n\nSubstitute $ x = 4 $ into $ q(x) $:\n\n$$\nq(4) = 3(4) - b = 12 - b\n$$\n\n---\n\n### Step 2: Plug $ q(4) $ into $ p(x) $\n
Now substitute $ q(4) = 12 - b $ into $ p(x) $:\n\n$$\np(q(4)) = p(12 - b) = 2(12 - b) - 7\n$$\n\nSimplify:\n\n$$\n2(12 - b) - 7 = 24 - 2b - 7 = 17 - 2b\n$$\n\n---\n\n### Step 3: Set equal to the given value\n\nWe are told that $ p(q(4)) = 7 $, so:\n\n$$\n17 - 2b = 7\n$$\n\nSolve for $ b $:\n\n$$\n-2b = 7 - 17 \\\n-2b = -10 \\\nb = \frac{-10}{-2} = 5\n$$\n\n---\n\n### Final Answer\n\n$$\n\\boxed{5}\n$$

Example output:
{"step": 1, "content": "<think>Okay, let's see. I need to find the value of \( b \) given that \( p(x) = 2x - 7 \) and \( q(x) = 3x - b \), and \( p(q(4)) = 7 \). Hmm, let's break this down step by step.\n\nFirst, I remember that when you have a composite function like \( p(q(x)) \), you substitute \( q(x) \) into \( p \). So \( p(q(4)) \) means first find \( q(4) \), then plug that result into \( p \).\n\nLet's start with \( q(4) \). Since \( q(x) = 3x - b \), substituting \( x = 4 \) gives:\n\n\( q(4) = 3(4) - b = 12 - b \).\n\nNow, we need to plug this into \( p \). The function \( p(x) = 2x - 7 \), so \( p(q(4)) = p(12 - b) \). Let's compute that:\n\n\( p(12 - b) = 2(12 - b) - 7 \).\n\nLet's simplify that expression:\n\nFirst, distribute the 2: \( 2 \\times 12 = 24 \) and \( 2 \\times (-b) = -2b \), so \( 2(12 - b) = 24 - 2b \).\n\nThen subtract 7: \( 24 - 2b - 7 = 17 - 2b \).\n\nWe are told that \( p(q(4)) = 7 \), so set the expression equal to 7:\n\n\( 17 - 2b = 7 \).\n\nNow, solve for \( b \). Let's subtract 17 from both sides:\n\n\( -2b = 7 - 17 \)\n\n\( -2b = -10 \)\n\nThen divide both sides by -2:\n\n\( b = \\frac{-10}{-2} = 5 \).\n\n"}
{"step": 2, "content": "Let me check that to make sure. If \( b = 5 \), then \( q(x) = 3x - 5 \). So \( q(4) = 3(4) - 5 = 12 - 5 = 7 \). Then \( p(q(4)) = p(7) = 2(7) - 7 = 14 - 7 = 7 \), which matches the given condition. So that checks out.\n\n"}
{"step": 3, "content": "I think that's right. Let me just go through the steps again to be sure. First, compute \( q(4) \) as 12 - b. Then plug into p: 2*(12 - b) - 7 = 24 - 2b - 7 = 17 - 2b. Set equal to 7: 17 - 2b = 7. Subtract 17: -2b = -10. Divide by -2: b = 5. Yep, that seems correct. I don't see any mistakes here.\n\n**Final Answer**\nThe value of \( b \) is \(\\boxed{5}\).<\\think>\n"}
{"step": 4, "content": "To find the value of $ b $, we are given two functions:\n\n- $ p(x) = 2x - 7 $\n- $ q(x) = 3x - b $\n\nand the condition that:\n\n$$\np(q(4)) = 7\n$$
\n---\n\n### Step 1: Compute $ q(4) $\n\nSubstitute $ x = 4 $ into $ q(x) $:\n\n$$\nq(4) = 3(4) - b = 12 - b\n$$\n\n---\n\n### Step 2: Plug $ q(4) $ into $ p(x) $\n
Now substitute $ q(4) = 12 - b $ into $ p(x) $:\n\n$$\np(q(4)) = p(12 - b) = 2(12 - b) - 7\n$$\n\nSimplify:\n\n$$\n2(12 - b) - 7 = 24 - 2b - 7 = 17 - 2b\n$$\n\n---\n\n### Step 3: Set equal to the given value\n\nWe are told that $ p(q(4)) = 7 $, so:\n\n$$\n17 - 2b = 7\n$$\n\nSolve for $ b $:\n\n$$\n-2b = 7 - 17 \\\n-2b = -10 \\\nb = \frac{-10}{-2} = 5\n$$\n\n---\n\n### Final Answer\n\n$$\n\\boxed{5}\n$$"}
'''

SPLIT_INPUT = "\nNow process the following new input:\nQuestion: {question}\nSolution: {solution}\n/no_think"

SPLIT_PROMPT_SPLITED = "{splition}/no_think"
# 由来，进展，未来可做的点。

